config/routes.rb
Cooluncool::Application.routes.draw do

  root :to => 'images#index'
  resources :images do
    collection do
      get 'cool'
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "640x480>", :thumb => "100x100>" }
  validates :image, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :image
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "640x480>", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @new_image = Image.last
    @top_images = Image.order("rating DESC").take(5)
    @image = Image.new
  end

  def create
    @image = Image.create(params[:image])
    @image.save
    redirect_to :action => "index"
  end

  def cool
    new_image = Image.last
    new_image.rating += 1
    new_image.save
    cookies.permanent[new_image.id] = true
    redirect_to :action => "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/index.html.erb
<div class="container">
  <% if @new_image %>
    <%= link_to image_tag(@new_image.image.url(:medium)), @new_image.image.url %>
    <p><span class="badge badge-success"><%= @new_image.rating %></span><p>
  <% end %>
  <p>
    <% unless @new_image and cookies[@new_image.id] %>
      <%= link_to 'Cool', cool_images_url, :class => "btn btn-large btn-success" %>
    <% else %>
      <button class="btn btn-large btn-success disabled" type="button">Cool</button>
    <% end %>
    <a class="btn btn-large btn-danger" data-toggle="modal" href="#uncool">Uncool</a>
  </p>
  <div class="row">
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f7380f641608d8f"></script>
<!-- AddThis Button END -->
  </div>
  <h2>Coolest images</h2>
  <ul id="top-images" class="unstyled">
  <% @top_images.each do |image| %>
    <li>
      <%= link_to image_tag(image.image.url(:thumb)), image.image.url %>
      <p><span class="badge badge-success"><%= image.rating %></span></p>
    </li>
  <% end %>
  </ul>
</div>
<div class="modal hide fade" id="uncool">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h1>So, what's cool?</h1>
  </div>
  <div class="modal-body">
    <%= form_for @image, :url => images_path, :html => { :method => :post, :multipart => true } do |form| %>
      <%= form.file_field :image %>
  </div>
  <div class="modal-footer">
      <%= form.submit "Upload image" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cooluncool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>